name: 'Updates TFVars with the Landing Zone details'
on: 
  workflow_call:
    inputs:
      TFC_REPO:
        description: 'Defines the URL that contains the workspace code'
        required: true
        type: string
      TFC_REPO_BRANCH:
        description: 'Defines the branch that contains the workspace code'
        required: true
        type: string
      TF_VARS_FILE:
        description: 'Defines the file that contains the TFVars'
        required: true
        type: string
      GCP_PROJECT_ID:
        description: 'Target GCP Project ID'
        required: true
        type: string
      GCP_REGION:
        description: 'Target GCP Region'
        required: true
        type: string
      GKE_CLUSTER_NAME:
        description: 'Target GKE Cluster Name'
        required: false
        type: string
      VPC_NAME:
        description: 'Target VPC Name'
        required: false
        type: string
      SUBNET_NAME:
        description: 'Target Subnet Name'
        required: false
        type: string

jobs:
  update-tfvars-file:
    runs-on: ubuntu-latest
    steps:
    - name: 'Define runtime variables'
      run: |
        # Define the temporary path for updating files
        mkdir ${{ github.workspace }}/temp
        echo "REPO_TEMP_PATH=${{ github.workspace }}/temp" >> $GITHUB_ENV
    - name: 'Checkout ${{ inputs.TFC_REPO }} that contains the Terraform workspace code'
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.TFC_REPO }}
        path: ${{ env.REPO_TEMP_PATH }}
        token: ${{ secrets.GH_TOKEN }}
        ref: ${{ inputs.TFC_REPO_BRANCH }}
    - name: 'Update ${{ inputs.TF_VARS_FILE }} file to use provided variables'
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '___'
        tokenSuffix: '___'
        files: '${{ env.REPO_TEMP_PATH }}/${{ inputs.TF_VARS_FILE }}'
      env:
        GCP_PROJECT_ID: ${{ inputs.GCP_PROJECT_ID }}
        GCP_REGION: ${{ inputs.GCP_REGION }}
        GKE_CLUSTER_NAME: ${{ inputs.GKE_CLUSTER_NAME}}
        VPC_NAME: ${{ inputs.VPC_NAME }}
        SUBNET_NAME: ${{ inputs.SUBNET_NAME }}
    # - uses: actions/checkout@v3
    - name: 'Update ${{ inputs.TF_VARS_FILE }} file to replace colons with equal signs'
      run: |
        cd ${{ env.REPO_TEMP_PATH }}
        sed -i 's/:/ =/g' ${{ inputs.TF_VARS_FILE }}
    - name: 'Commit and push changes made to ${{ inputs.TF_VARS_FILE }} file to the repo: ${{ inputs.TFC_REPO }}'
      run: |
          cd ${{ env.REPO_TEMP_PATH }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated ${{ inputs.TF_VARS_FILE }} file with inputs provided to the workflow"
          git push     